# Make sure to check the documentation at http://goreleaser.com

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh

builds:
  - env:
      - CGO_ENABLED=0

archives:
  - rlcp: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - tap:
      owner: mightymatth
      name: arcli
    homepage: https://github.com/mightymatth/arcli
    description: "Awesome Redmine CLI"
    install: |-
      bin.install "arcli"
      bash_completion.install "completions/arcli.bash" => "arcli"
      zsh_completion.install "completions/arcli.zsh" => "_arcli"
      fish_completion.install "completions/arcli.fish"
    test: |
      system "#{bin}/arcli --version"

snapcrafts:
  - summary: Awesome Redmine CLI
    publish: true # <- this line
    description: |
      CLI tool that makes Redmine awesome
    grade: stable
    confinement: strict
    license: MIT
    apps:
      arcli:
        command: arcli
        plugs: [ "home", "network" ]
